### ISSUE TITLE
Refactor Python scripts to Python CLI package

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/data-platform-workflows#24]
Python CLI package would be installed with `pip` or `pipx` so that the reusable workflows would not need to checkout `data-platform-workflows`.

For example, this
https://github.com/canonical/data-platform-workflows/blob/7de3f1c8b34f9ad460d83b440d38422bb3f44617/.github/workflows/release_charm.yaml#L54-L74
could be replaced by this
```yaml
 - name: Checkout
   uses: actions/checkout@v3 
 - name: Install Python CLI
   run: pipx install git+https://github.com/canonical/data-platform-workflows.git@${{ needs.get-workflow-version.outputs.version }}
 - name: Download .charm file(s) 
   uses: actions/download-artifact@v3 
   with: 
     name: ${{ inputs.artifact-name }} 
 - name: Upload & release charm 
   id: release 
   run: name-of-cli release_charm --charm-directory ${{ inputs.path-to-charm-directory }} --channel ${{ inputs.channel }} 
   env: 
     CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }} 
```

Also, pip dependencies would not need to be installed separately. For example, this could be removed
https://github.com/canonical/data-platform-workflows/blob/7de3f1c8b34f9ad460d83b440d38422bb3f44617/.github/workflows/release_charm.yaml#L45-L46
